In [1]:
# We import the libraries that we will need for the lab.
import pandas as pd # data handling and dataframes
import numpy as np # array handling and mathematical operations

# allows ignoring Python warnings
import warnings 
warnings.filterwarnings('ignore')

In [2]:
try:
    df2010 = pd.read_csv('../data/2010-21crim.csv')
except pd.errors.ParserError:
    print("Se produjo un error al analizar el archivo CSV.")

In [ ]:
df2010 = df2010.drop(columns=['Unnamed: 13'])

In [11]:
df2010

,Unnamed: 0,2021,2020,2019,2018,2017,2016,2015,2014,2013,2012,2011,2010
0,Total Nacional,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1. CONTRA LAS PERSONAS,183590.0,161406.0,186110.0,177165.0,174217.0,166431.0,223893.0,281713.0,274655.0,286446.0,300654.0,297488.0
2,1.1.-Homicidios dolosos/asesinatos,1322.0,1201.0,1167.0,1088.0,1106.0,1107.0,964.0,1048.0,964.0,1125.0,1210.0,1177.0
3,1.1.1.-Homicidios dolosos/asesinatos consu...,290.0,298.0,331.0,289.0,307.0,294.0,302.0,323.0,302.0,364.0,385.0,401.0
4,1.2.-Lesiones,96159.0,81449.0,103341.0,99928.0,100354.0,97108.0,97012.0,98821.0,100193.0,105913.0,112824.0,113067.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2473,12. OTRAS INFRACCIONES PENALES,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,2.0
2474,TOTAL INFRACCIONES PENALES,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,153.0,925.0
2475,Notas:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2476,(*) Se computan datos provenientes de la Polic...,Guardia Civil,policías autonómicas y policías locales que p...,ni de robos con violencia/intimidación en vía...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2477,Fuente: Ministerio del Interior,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
try:
    df2022 = pd.read_csv('../data/2022crim.csv')
except pd.errors.ParserError:
    print("Se produjo un error al analizar el archivo CSV.")

In [ ]:
df2022 = df2022.drop(columns=['Unnamed: 2'])

In [12]:
df2022

                              Unnamed: 0  Enero-diciembre 2022
0                            Araba/�lava                   NaN
1        III. TOTAL INFRACCIONES PENALES               14049.0
2                               Albacete                   NaN
3        III. TOTAL INFRACCIONES PENALES               15370.0
4                       Alicante/Alacant                   NaN
..                                   ...                   ...
101      III. TOTAL INFRACCIONES PENALES                3651.0
102                              Melilla                   NaN
103      III. TOTAL INFRACCIONES PENALES                4314.0
104                     En el extranjero                   NaN
105      III. TOTAL INFRACCIONES PENALES               10062.0

[106 rows x 2 columns]

In [7]:

list_year = ["2010","2011","2012","2013","2014","2015","2016","2017","2018","2019","2020","2021"]

name_year = {
    "name": [],
    "2022" : [],
    "2021" : [],
    "2020" : [],
    "2019" : [],
    "2018" : [],
    "2017" : [],
    "2016" : [],
    "2015" : [],
    "2014" : [],
    "2013" : [],
    "2012" : [],
    "2011" : [],
    "2010" : [],
}

for i in range(45, 2385, 45):  # Iterar desde la fila 45 hasta la fila 2384
    fila = df2010["Unnamed: 0"][i]
    name_year["name"].append(fila)
    
for e in  list_year:    
    for i in range(89, 2385, 45):  # Iterar desde la fila 45 hasta la fila 2384
        fila = df2010[e][i]
        name_year[e].append(fila)

for i in range(1,104,2):
    fila = df2022['Enero-diciembre 2022'][i]
    name_year['2022'].append(fila)

In [8]:
name_year

{'name': ['Araba/Álava',
  'Albacete',
  'Alicante/Alacant',
  'Almería',
  'Ávila',
  'Badajoz',
  'Balears (Illes)',
  'Barcelona',
  'Burgos',
  'Cáceres',
  'Cádiz',
  'Castellón/Castelló',
  'Ciudad Real',
  'Córdoba',
  'Coruña (A)',
  'Cuenca',
  'Girona',
  'Granada',
  'Guadalajara',
  'Gipuzkoa',
  'Huelva',
  'Huesca',
  'Jaén',
  'León',
  'Lleida',
  'Rioja (La)',
  'Lugo',
  'Madrid',
  'Málaga',
  'Murcia',
  'Navarra',
  'Ourense',
  'Asturias',
  'Palencia',
  'Palmas (Las)',
  'Pontevedra',
  'Salamanca',
  'Santa Cruz de Tenerife',
  'Cantabria',
  'Segovia',
  'Sevilla',
  'Soria',
  'Tarragona',
  'Teruel',
  'Toledo',
  'Valencia/València',
  'Valladolid',
  'Bizkaia',
  'Zamora',
  'Zaragoza',
  'Ceuta',
  'Melilla'],
 '2022': [14049.0,
  15370.0,
  94363.0,
  29902.0,
  5273.0,
  21349.0,
  75942.0,
  362817.0,
  13378.0,
  10761.0,
  56261.0,
  25772.0,
  15935.0,
  28512.0,
  42729.0,
  7056.0,
  47274.0,
  37594.0,
  11714.0,
  29012.0,
  21349.0,
  7324.0,
  19824.0,
  16495.0,
  21615.0,
  11797.0,
  8275.0,
  402961.0,
  91971.0,
  68678.0,
  33422.0,
  9392.0,
  32146.0,
  5061.0,
  52954.0,
  34652.0,
  12367.0,
  42688.0,
  23713.0,
  5401.0,
  94127.0,
  3403.0,
  43313.0,
  3583.0,
  30916.0,
  143090.0,
  20363.0,
  58660.0,
  5390.0,
  37338.0,
  3651.0,
  4314.0],
 '2021': ['11383.0',
  '11777.0',
  '78916.0',
  '26110.0',
  '5185.0',
  '18082.0',
  '61015.0',
  '295666.0',
  '11920.0',
  '9184.0',
  '46798.0',
  '22183.0',
  '13328.0',
  '23307.0',
  '40456.0',
  '6167.0',
  '39345.0',
  '31712.0',
  '9442.0',
  '24331.0',
  '17727.0',
  '6088.0',
  '16422.0',
  '13219.0',
  '18563.0',
  '9115.0',
  '8032.0',
  '345987.0',
  '76049.0',
  '57974.0',
  '26719.0',
  '8635.0',
  '26340.0',
  '4306.0',
  '46446.0',
  '31132.0',
  '9677.0',
  '34786.0',
  '19894.0',
  '4449.0',
  '76769.0',
  '2550.0',
  '36782.0',
  '2948.0',
  '26698.0',
  '124238.0',
  '18073.0',
  '49067.0',
  '4629.0',
  '32760.0',
  '3916.0',
  '4116.0'],
 '2020': ['10641.0',
  '10728.0',
  '72732.0',
  '23627.0',
  '4447.0',
  '17027.0',
  '59750.0',
  '270214.0',
  '10236.0',
  '8014.0',
  '42734.0',
  '18373.0',
  '11715.0',
  '21938.0',
  '31992.0',
  '5401.0',
  '34760.0',
  '28840.0',
  '8535.0',
  '21846.0',
  '16426.0',
  '5289.0',
  '15088.0',
  '12530.0',
  '15593.0',
  '7827.0',
  '6877.0',
  '310194.0',
  '66451.0',
  '50969.0',
  '23596.0',
  '7435.0',
  '24324.0',
  '3755.0',
  '48146.0',
  '27040.0',
  '8520.0',
  '35489.0',
  '16585.0',
  '4119.0',
  '72490.0',
  '2242.0',
  '32485.0',
  '2361.0',
  '25529.0',
  '102117.0',
  '15030.0',
  '44689.0',
  '4146.0',
  '28374.0',
  '3648.0',
  '4470.0'],
 '2019': ['13011.0',
  '13105.0',
  '87979.0',
  '27579.0',
  '5054.0',
  '18962.0',
  '77662.0',
  '385838.0',
  '12351.0',
  '8629.0',
  '50663.0',
  '23184.0',
  '13029.0',
  '25211.0',
  '35472.0',
  '6222.0',
  '45249.0',
  '33347.0',
  '9795.0',
  '25016.0',
  '18959.0',
  '5551.0',
  '16283.0',
  '15536.0',
  '18621.0',
  '8750.0',
  '7490.0',
  '407736.0',
  '80057.0',
  '57099.0',
  '29170.0',
  '8179.0',
  '27163.0',
  '4248.0',
  '52755.0',
  '28883.0',
  '9788.0',
  '42884.0',
  '18073.0',
  '4353.0',
  '87222.0',
  '2565.0',
  '39557.0',
  '2746.0',
  '28157.0',
  '121386.0',
  '17888.0',
  '56509.0',
  '4580.0',
  '34286.0',
  '4746.0',
  '5582.0'],
 '2018': [12781.0,
  12691.0,
  88636.0,
  28304.0,
  4893.0,
  18409.0,
  73661.0,
  369375.0,
  11673.0,
  8404.0,
  50813.0,
  24030.0,
  12349.0,
  25561.0,
  35333.0,
  5979.0,
  43297.0,
  33709.0,
  9765.0,
  23817.0,
  18937.0,
  5060.0,
  15989.0,
  15684.0,
  19047.0,
  8274.0,
  7555.0,
  389914.0,
  79225.0,
  55398.0,
  27269.0,
  7792.0,
  26433.0,
  4262.0,
  48868.0,
  27846.0,
  10163.0,
  41781.0,
  17674.0,
  4106.0,
  82303.0,
  2325.0,
  39791.0,
  2760.0,
  27548.0,
  118961.0,
  17166.0,
  53655.0,
  4591.0,
  32547.0,
  4722.0,
  5488.0],
 '2017': [12138.0,
  11786.0,
  90343.0,
  29401.0,
  4676.0,
  18749.0,
  72157.0,
  327845.0,
  11160.0,
  7662.0,
  50174.0,
  22748.0,
  12335.0,
  24900.0,
  33232.0,
  5723.0,
  39515.0,
  33866.0,
  8662.0,
  22281.0,
  19439.0,
  4941.0,
  15816.0,
  14646.0,
  17231.0,
  7877.0,
  6961.0,
  381242.0,
  77280.0,
  52690.0,
  24827.0,
  7222.0,
  25652.0,
  4026.0,
  48539.0,
  26759.0,
  9865.0,
  42820.0,
  17440.0,
  4176.0,
  83455.0,
  2334.0,
  37695.0,
  2409.0,
  25500.0,
  114011.0,
  16434.0,
  49268.0,
  4557.0,
  30528.0,
  4503.0,
  4744.0],
 '2016': [11854.0,
  11361.0,
  91352.0,
  30617.0,
  4743.0,
  18359.0,
  68160.0,
  311780.0,
  11044.0,
  7927.0,
  50000.0,
  23924.0,
  12793.0,
  23891.0,
  32559.0,
  5768.0,
  37509.0,
  32311.0,
  8652.0,
  22079.0,
  19865.0,
  4984.0,
  16593.0,
  14986.0,
  17439.0,
  7997.0,
  7097.0,
  373402.0,
  78232.0,
  51309.0,
  25704.0,
  7423.0,
  26093.0,
  3862.0,
  46462.0,
  27326.0,
  9918.0,
  42320.0,
  17002.0,
  4401.0,
  80327.0,
  2309.0,
  37200.0,
  2534.0,
  25005.0,
  114933.0,
  16334.0,
  48876.0,
  4440.0,
  30628.0,
  4633.0,
  4832.0],
 '2015': [12501.0,
  12105.0,
  92776.0,
  30639.0,
  4907.0,
  18906.0,
  66680.0,
  316947.0,
  11145.0,
  8345.0,
  53791.0,
  25108.0,
  14270.0,
  25497.0,
  32658.0,
  5781.0,
  40551.0,
  32173.0,
  8969.0,
  23543.0,
  19429.0,
  5054.0,
  17009.0,
  15377.0,
  18958.0,
  8527.0,
  7244.0,
  365006.0,
  76315.0,
  53374.0,
  23932.0,
  7588.0,
  26982.0,
  3930.0,
  47166.0,
  29130.0,
  10159.0,
  42373.0,
  16754.0,
  4597.0,
  82271.0,
  2317.0,
  39008.0,
  2591.0,
  25853.0,
  116841.0,
  17573.0,
  49457.0,
  4498.0,
  30739.0,
  4961.0,
  4896.0],
 '2014': [12640.0,
  13029.0,
  97408.0,
  31209.0,
  5149.0,
  19758.0,
  68747.0,
  319576.0,
  11950.0,
  8463.0,
  55463.0,
  26843.0,
  14193.0,
  27114.0,
  32101.0,
  5891.0,
  42051.0,
  34098.0,
  9381.0,
  23994.0,
  21021.0,
  5338.0,
  17856.0,
  16102.0,
  18966.0,
  8925.0,
  7479.0,
  365599.0,
  78076.0,
  52655.0,
  26558.0,
  8175.0,
  28430.0,
  4292.0,
  48543.0,
  30498.0,
  8966.0,
  41590.0,
  17187.0,
  4765.0,
  87384.0,
  2344.0,
  42271.0,
  2976.0,
  27704.0,
  123120.0,
  18919.0,
  51597.0,
  4526.0,
  32146.0,
  5302.0,
  4618.0],
 '2013': [13285.0,
  13943.0,
  100886.0,
  32565.0,
  5513.0,
  20475.0,
  73833.0,
  326444.0,
  12120.0,
  8863.0,
  56619.0,
  27956.0,
  15028.0,
  28713.0,
  32381.0,
  6207.0,
  41894.0,
  36662.0,
  9538.0,
  23583.0,
  21678.0,
  5600.0,
  17913.0,
  16324.0,
  20310.0,
  9564.0,
  7696.0,
  379114.0,
  88670.0,
  54624.0,
  23911.0,
  9199.0,
  30049.0,
  4361.0,
  50212.0,
  31961.0,
  9271.0,
  43129.0,
  17239.0,
  4985.0,
  91026.0,
  2548.0,
  43266.0,
  3138.0,
  28747.0,
  131446.0,
  20192.0,
  53731.0,
  4590.0,
  33997.0,
  5850.0,
  4696.0],
 '2012': [14062.0,
  14269.0,
  107583.0,
  34906.0,
  5668.0,
  20198.0,
  74558.0,
  343958.0,
  13242.0,
  9272.0,
  59863.0,
  28908.0,
  15837.0,
  29516.0,
  33872.0,
  6390.0,
  43078.0,
  39276.0,
  9776.0,
  24402.0,
  22279.0,
  5699.0,
  19254.0,
  17128.0,
  20930.0,
  10154.0,
  8032.0,
  393872.0,
  96767.0,
  57449.0,
  21635.0,
  8841.0,
  30164.0,
  4726.0,
  52187.0,
  32435.0,
  9743.0,
  45786.0,
  18297.0,
  5458.0,
  93079.0,
  2809.0,
  45190.0,
  3368.0,
  28131.0,
  141426.0,
  20666.0,
  54144.0,
  4960.0,
  37334.0,
  7052.0,
  4639.0],
 '2011': [14693.0,
  14304.0,
  112576.0,
  35543.0,
  5674.0,
  20372.0,
  74455.0,
  346665.0,
  13919.0,
  9107.0,
  60277.0,
  28610.0,
  15645.0,
  29521.0,
  33479.0,
  6515.0,
  42775.0,
  41135.0,
  9981.0,
  23734.0,
  22700.0,
  6112.0,
  19636.0,
  17038.0,
  20381.0,
  9998.0,
  7925.0,
  393029.0,
  102373.0,
  57882.0,
  20780.0,
  7984.0,
  29158.0,
  4855.0,
  52463.0,
  32427.0,
  9693.0,
  46479.0,
  18249.0,
  5393.0,
  95935.0,
  2800.0,
  45050.0,
  3329.0,
  28015.0,
  143510.0,
  19816.0,
  51140.0,
  4621.0,
  40769.0,
  6294.0,
  4942.0],
 '2010': [14948.0,
  13931.0,
  113114.0,
  36141.0,
  5621.0,
  20700.0,
  70162.0,
  353910.0,
  14185.0,
  9316.0,
  60781.0,
  28829.0,
  15670.0,
  29505.0,
  32471.0,
  6557.0,
  44854.0,
  42652.0,
  9700.0,
  24260.0,
  20751.0,
  6024.0,
  19897.0,
  16528.0,
  19979.0,
  9448.0,
  7437.0,
  401871.0,
  104709.0,
  57769.0,
  19474.0,
  7314.0,
  28481.0,
  4917.0,
  49574.0,
  30326.0,
  10680.0,
  44391.0,
  17487.0,
  5154.0,
  94960.0,
  2792.0,
  46180.0,
  3321.0,
  25745.0,
  145215.0,
  20311.0,
  50967.0,
  4321.0,
  41869.0,
  5974.0,
  4652.0]}

In [9]:
df = pd.DataFrame(name_year)
df

,name,2022,2021,2020,2019,2018,2017,2016,2015,2014,2013,2012,2011,2010
0,Araba/Álava,14049.0,11383.0,10641.0,13011.0,12781.0,12138.0,11854.0,12501.0,12640.0,13285.0,14062.0,14693.0,14948.0
1,Albacete,15370.0,11777.0,10728.0,13105.0,12691.0,11786.0,11361.0,12105.0,13029.0,13943.0,14269.0,14304.0,13931.0
2,Alicante/Alacant,94363.0,78916.0,72732.0,87979.0,88636.0,90343.0,91352.0,92776.0,97408.0,100886.0,107583.0,112576.0,113114.0
3,Almería,29902.0,26110.0,23627.0,27579.0,28304.0,29401.0,30617.0,30639.0,31209.0,32565.0,34906.0,35543.0,36141.0
4,Ávila,5273.0,5185.0,4447.0,5054.0,4893.0,4676.0,4743.0,4907.0,5149.0,5513.0,5668.0,5674.0,5621.0
5,Badajoz,21349.0,18082.0,17027.0,18962.0,18409.0,18749.0,18359.0,18906.0,19758.0,20475.0,20198.0,20372.0,20700.0
6,Balears (Illes),75942.0,61015.0,59750.0,77662.0,73661.0,72157.0,68160.0,66680.0,68747.0,73833.0,74558.0,74455.0,70162.0
7,Barcelona,362817.0,295666.0,270214.0,385838.0,369375.0,327845.0,311780.0,316947.0,319576.0,326444.0,343958.0,346665.0,353910.0
8,Burgos,13378.0,11920.0,10236.0,12351.0,11673.0,11160.0,11044.0,11145.0,11950.0,12120.0,13242.0,13919.0,14185.0
9,Cáceres,10761.0,9184.0,8014.0,8629.0,8404.0,7662.0,7927.0,8345.0,8463.0,8863.0,9272.0,9107.0,9316.0
10,Cádiz,56261.0,46798.0,42734.0,50663.0,50813.0,50174.0,50000.0,53791.0,55463.0,56619.0,59863.0,60277.0,60781.0
11,Castellón/Castelló,25772.0,22183.0,18373.0,23184.0,24030.0,22748.0,23924.0,25108.0,26843.0,27956.0,28908.0,28610.0,28829.0
12,Ciudad Real,15935.0,13328.0,11715.0,13029.0,12349.0,12335.0,12793.0,14270.0,14193.0,15028.0,15837.0,15645.0,15670.0
13,Córdoba,28512.0,23307.0,21938.0,25211.0,25561.0,24900.0,23891.0,25497.0,27114.0,28713.0,29516.0,29521.0,29505.0
14,Coruña (A),42729.0,40456.0,31992.0,35472.0,35333.0,33232.0,32559.0,32658.0,32101.0,32381.0,33872.0,33479.0,32471.0
15,Cuenca,7056.0,6167.0,5401.0,6222.0,5979.0,5723.0,5768.0,5781.0,5891.0,6207.0,6390.0,6515.0,6557.0
16,Girona,47274.0,39345.0,34760.0,45249.0,43297.0,39515.0,37509.0,40551.0,42051.0,41894.0,43078.0,42775.0,44854.0
17,Granada,37594.0,31712.0,28840.0,33347.0,33709.0,33866.0,32311.0,32173.0,34098.0,36662.0,39276.0,41135.0,42652.0
18,Guadalajara,11714.0,9442.0,8535.0,9795.0,9765.0,8662.0,8652.0,8969.0,9381.0,9538.0,9776.0,9981.0,9700.0
19,Gipuzkoa,29012.0,24331.0,21846.0,25016.0,23817.0,22281.0,22079.0,23543.0,23994.0,23583.0,24402.0,23734.0,24260.0
20,Huelva,21349.0,17727.0,16426.0,18959.0,18937.0,19439.0,19865.0,19429.0,21021.0,21678.0,22279.0,22700.0,20751.0
21,Huesca,7324.0,6088.0,5289.0,5551.0,5060.0,4941.0,4984.0,5054.0,5338.0,5600.0,5699.0,6112.0,6024.0
22,Jaén,19824.0,16422.0,15088.0,16283.0,15989.0,15816.0,16593.0,17009.0,17856.0,17913.0,19254.0,19636.0,19897.0
23,León,16495.0,13219.0,12530.0,15536.0,15684.0,14646.0,14986.0,15377.0,16102.0,16324.0,17128.0,17038.0,16528.0
24,Lleida,21615.0,18563.0,15593.0,18621.0,19047.0,17231.0,17439.0,18958.0,18966.0,20310.0,20930.0,20381.0,19979.0
25,Rioja (La),11797.0,9115.0,7827.0,8750.0,8274.0,7877.0,7997.0,8527.0,8925.0,9564.0,10154.0,9998.0,9448.0
26,Lugo,8275.0,8032.0,6877.0,7490.0,7555.0,6961.0,7097.0,7244.0,7479.0,7696.0,8032.0,7925.0,7437.0
27,Madrid,402961.0,345987.0,310194.0,407736.0,389914.0,381242.0,373402.0,365006.0,365599.0,379114.0,393872.0,393029.0,401871.0
28,Málaga,91971.0,76049.0,66451.0,80057.0,79225.0,77280.0,78232.0,76315.0,78076.0,88670.0,96767.0,102373.0,104709.0
29,Murcia,68678.0,57974.0,50969.0,57099.0,55398.0,52690.0,51309.0,53374.0,52655.0,54624.0,57449.0,57882.0,57769.0
30,Navarra,33422.0,26719.0,23596.0,29170.0,27269.0,24827.0,25704.0,23932.0,26558.0,23911.0,21635.0,20780.0,19474.0
31,Ourense,9392.0,8635.0,7435.0,8179.0,7792.0,7222.0,7423.0,7588.0,8175.0,9199.0,8841.0,7984.0,7314.0
32,Asturias,32146.0,26340.0,24324.0,27163.0,26433.0,25652.0,26093.0,26982.0,28430.0,30049.0,30164.0,29158.0,28481.0
33,Palencia,5061.0,4306.0,3755.0,4248.0,4262.0,4026.0,3862.0,3930.0,4292.0,4361.0,4726.0,4855.0,4917.0
34,Palmas (Las),52954.0,46446.0,48146.0,52755.0,48868.0,48539.0,46462.0,47166.0,48543.0,50212.0,52187.0,52463.0,49574.0
35,Pontevedra,34652.0,31132.0,27040.0,28883.0,27846.0,26759.0,27326.0,29130.0,30498.0,31961.0,32435.0,32427.0,30326.0
36,Salamanca,12367.0,9677.0,8520.0,9788.0,10163.0,9865.0,9918.0,10159.0,8966.0,9271.0,9743.0,9693.0,10680.0
37,Santa Cruz de Tenerife,42688.0,34786.0,35489.0,42884.0,41781.0,42820.0,42320.0,42373.0,41590.0,43129.0,45786.0,46479.0,44391.0
38,Cantabria,23713.0,19894.0,16585.0,18073.0,17674.0,17440.0,17002.0,16754.0,17187.0,17239.0,18297.0,18249.0,17487.0
39,Segovia,5401.0,4449.0,4119.0,4353.0,4106.0,4176.0,4401.0,4597.0,4765.0,4985.0,5458.0,5393.0,5154.0
40,Sevilla,94127.0,76769.0,72490.0,87222.0,82303.0,83455.0,80327.0,82271.0,87384.0,91026.0,93079.0,95935.0,94960.0
41,Soria,3403.0,2550.0,2242.0,2565.0,2325.0,2334.0,2309.0,2317.0,2344.0,2548.0,2809.0,2800.0,2792.0
42,Tarragona,43313.0,36782.0,32485.0,39557.0,39791.0,37695.0,37200.0,39008.0,42271.0,43266.0,45190.0,45050.0,46180.0
43,Teruel,3583.0,2948.0,2361.0,2746.0,2760.0,2409.0,2534.0,2591.0,2976.0,3138.0,3368.0,3329.0,3321.0
44,Toledo,30916.0,26698.0,25529.0,28157.0,27548.0,25500.0,25005.0,25853.0,27704.0,28747.0,28131.0,28015.0,25745.0
45,Valencia/València,143090.0,124238.0,102117.0,121386.0,118961.0,114011.0,114933.0,116841.0,123120.0,131446.0,141426.0,143510.0,145215.0
46,Valladolid,20363.0,18073.0,15030.0,17888.0,17166.0,16434.0,16334.0,17573.0,18919.0,20192.0,20666.0,19816.0,20311.0
47,Bizkaia,58660.0,49067.0,44689.0,56509.0,53655.0,49268.0,48876.0,49457.0,51597.0,53731.0,54144.0,51140.0,50967.0
48,Zamora,5390.0,4629.0,4146.0,4580.0,4591.0,4557.0,4440.0,4498.0,4526.0,4590.0,4960.0,4621.0,4321.0
49,Zaragoza,37338.0,32760.0,28374.0,34286.0,32547.0,30528.0,30628.0,30739.0,32146.0,33997.0,37334.0,40769.0,41869.0
50,Ceuta,3651.0,3916.0,3648.0,4746.0,4722.0,4503.0,4633.0,4961.0,5302.0,5850.0,7052.0,6294.0,5974.0
51,Melilla,4314.0,4116.0,4470.0,5582.0,5488.0,4744.0,4832.0,4896.0,4618.0,4696.0,4639.0,4942.0,4652.0

In [13]:
df.to_csv('../data/crims2010-22.csv')